export type REQUEST_TEABAGS = 'REQUEST_TEABAGS';
export const REQUEST_TEABAGS: REQUEST_TEABAGS = 'REQUEST_TEABAGS';

export type RECEIVE_TEABAGS = 'RECEIVE_TEABAGS';
export const RECEIVE_TEABAGS: RECEIVE_TEABAGS = 'RECEIVE_TEABAGS';

export type SEARCH_TERMS_ERROR = 'SEARCH_TERMS_ERROR';
export const SEARCH_TERMS_ERROR: SEARCH_TERMS_ERROR = 'SEARCH_TERMS_ERROR';

export type ZOOM_IMAGE_TOGGLE = 'ZOOM_IMAGE_TOGGLE';
export const ZOOM_IMAGE_TOGGLE: ZOOM_IMAGE_TOGGLE = 'ZOOM_IMAGE_TOGGLE';
