export type REQUEST_TEABAG = 'REQUEST_TEABAG';
export const REQUEST_TEABAG: REQUEST_TEABAG = 'REQUEST_TEABAG';

export type RECEIVE_TEABAG = 'RECEIVE_TEABAG';
export const RECEIVE_TEABAG: RECEIVE_TEABAG = 'RECEIVE_TEABAG';

export type CHANGE_BRAND = 'CHANGE_BRAND';
export const CHANGE_BRAND: CHANGE_BRAND = 'CHANGE_BRAND';

export type CLEAR_BRAND = 'CLEAR_BRAND';
export const CLEAR_BRAND: CLEAR_BRAND = 'CLEAR_BRAND';

export type CHANGE_BAGTYPE = 'CHANGE_BAGTYPE';
export const CHANGE_BAGTYPE: CHANGE_BAGTYPE = 'CHANGE_BAGTYPE';

export type CLEAR_BAGTYPE = 'CLEAR_BAGTYPE';
export const CLEAR_BAGTYPE: CLEAR_BAGTYPE = 'CLEAR_BAGTYPE';

export type CHANGE_COUNTRY = 'CHANGE_COUNTRY';
export const CHANGE_COUNTRY: CHANGE_COUNTRY = 'CHANGE_COUNTRY';

export type CLEAR_COUNTRY = 'CLEAR_COUNTRY';
export const CLEAR_COUNTRY: CLEAR_COUNTRY = 'CLEAR_COUNTRY';
