export type REQUEST_BAGTYPECOUNT = 'REQUEST_BAGTYPECOUNT';
export const REQUEST_BAGTYPECOUNT: REQUEST_BAGTYPECOUNT = 'REQUEST_BAGTYPECOUNT';

export type RECIEVE_BAGTYPECOUNT = 'RECIEVE_BAGTYPECOUNT';
export const RECIEVE_BAGTYPECOUNT: RECIEVE_BAGTYPECOUNT = 'RECIEVE_BAGTYPECOUNT';

export type REQUEST_BRANDCOUNT = 'REQUEST_BRANDCOUNT';
export const REQUEST_BRANDCOUNT: REQUEST_BRANDCOUNT = 'REQUEST_BRANDCOUNT';

export type RECIEVE_BRANDCOUNT = 'RECIEVE_BRANDCOUNT';
export const RECIEVE_BRANDCOUNT: RECIEVE_BRANDCOUNT = 'RECIEVE_BRANDCOUNT';

export const BAGSCOUNTBYBRAND = `/api/Tea/Dashboards/Brands/`;
export const BAGSCOUNTBYBAGTYPES = `/api/Tea/Dashboards/BagTypes/`;
export const BAGSCOUNTBYPERIOD = `/api/Tea/Dashboards/Periods/`;
export const TOTALBAGSCOUNTBYPERIOD = `/api/Tea/Dashboards/TotalCountPeriod/`;
