export type REQUEST_BAGTYPECOUNT = 'REQUEST_BAGTYPECOUNT';
export const REQUEST_BAGTYPECOUNT: REQUEST_BAGTYPECOUNT = 'REQUEST_BAGTYPECOUNT';

export type RECIEVE_BAGTYPECOUNT = 'RECIEVE_BAGTYPECOUNT';
export const RECIEVE_BAGTYPECOUNT: RECIEVE_BAGTYPECOUNT = 'RECIEVE_BAGTYPECOUNT';

export type REQUEST_BRANDCOUNT = 'REQUEST_BRANDCOUNT';
export const REQUEST_BRANDCOUNT: REQUEST_BRANDCOUNT = 'REQUEST_BRANDCOUNT';

export type RECIEVE_BRANDCOUNT = 'RECIEVE_BRANDCOUNT';
export const RECIEVE_BRANDCOUNT: RECIEVE_BRANDCOUNT = 'RECIEVE_BRANDCOUNT';

export type REQUEST_COUNTBYPERIOD = 'REQUEST_COUNTBYPERIOD';
export const REQUEST_COUNTBYPERIOD: REQUEST_COUNTBYPERIOD = 'REQUEST_COUNTBYPERIOD';

export type RECIEVE_COUNTBYPERIOD = 'RECIEVE_COUNTBYPERIOD';
export const RECIEVE_COUNTBYPERIOD: RECIEVE_COUNTBYPERIOD = 'RECIEVE_COUNTBYPERIOD';

export const BAGSCOUNTBYPERIOD = `/api/tea/Dashboards/Periods/`;
