export type REQUEST_BAGTYPECOUNT = 'REQUEST_BAGTYPECOUNT';
export const REQUEST_BAGTYPECOUNT: REQUEST_BAGTYPECOUNT = 'REQUEST_BAGTYPECOUNT';

export type RECIEVE_BAGTYPECOUNT = 'RECIEVE_BAGTYPECOUNT';
export const RECIEVE_BAGTYPECOUNT: RECIEVE_BAGTYPECOUNT = 'RECIEVE_BAGTYPECOUNT';

