export type UPDATE_COUNTBYREFVALUE = 'UPDATE_COUNTBYREFVALUE';
export const UPDATE_COUNTBYREFVALUE: UPDATE_COUNTBYREFVALUE = 'UPDATE_COUNTBYREFVALUE';

export type REQUEST_COUNTBYREFVALUE = 'REQUEST_COUNTBYREFVALUE';
export const REQUEST_COUNTBYREFVALUE: REQUEST_COUNTBYREFVALUE = 'REQUEST_COUNTBYREFVALUE';

export type RECIEVE_COUNTBYREFVALUE = 'RECIEVE_COUNTBYREFVALUE';
export const RECIEVE_COUNTBYREFVALUE: RECIEVE_COUNTBYREFVALUE = 'RECIEVE_COUNTBYREFVALUE';

export type UPDATE_COUNTBYPERIOD = 'UPDATE_COUNTBYPERIOD';
export const UPDATE_COUNTBYPERIOD: UPDATE_COUNTBYPERIOD = 'UPDATE_COUNTBYPERIOD';

export type REQUEST_COUNTBYPERIOD = 'REQUEST_COUNTBYPERIOD';
export const REQUEST_COUNTBYPERIOD: REQUEST_COUNTBYPERIOD = 'REQUEST_COUNTBYPERIOD';

export type RECIEVE_COUNTBYPERIOD = 'RECIEVE_COUNTBYPERIOD';
export const RECIEVE_COUNTBYPERIOD: RECIEVE_COUNTBYPERIOD = 'RECIEVE_COUNTBYPERIOD';

export type CHANGE_CHARTTYPE = 'CHANGE_CHARTTYPE';
export const CHANGE_CHARTTYPE: CHANGE_CHARTTYPE = 'CHANGE_CHARTTYPE';

export type CHANGE_CHARTPERIOD = 'CHANGE_CHARTPERIOD';
export const CHANGE_CHARTPERIOD: CHANGE_CHARTPERIOD = 'CHANGE_CHARTPERIOD';
