export type REQUEST_COUNTBYPERIOD = 'REQUEST_COUNTBYPERIOD';
export const REQUEST_COUNTBYPERIOD: REQUEST_COUNTBYPERIOD = 'REQUEST_COUNTBYPERIOD';

export type RECIEVE_COUNTBYPERIOD = 'RECIEVE_COUNTBYPERIOD';
export const RECIEVE_COUNTBYPERIOD: RECIEVE_COUNTBYPERIOD = 'RECIEVE_COUNTBYPERIOD';

export type CHANGE_CHARTTYPE = 'CHANGE_CHARTTYPE';
export const CHANGE_CHARTTYPE: CHANGE_CHARTTYPE = 'CHANGE_CHARTTYPE';
