export type REQUEST_COUNTRY = 'REQUEST_COUNTRY';
export const REQUEST_COUNTRY: REQUEST_COUNTRY = 'REQUEST_COUNTRY';

export type RECIEVE_COUNTRY = 'RECIEVE_COUNTRY';
export const RECIEVE_COUNTRY: RECIEVE_COUNTRY = 'RECIEVE_COUNTRY';

export type ADD_COUNTRY = 'ADD_COUNTRY';
export const ADD_COUNTRY: ADD_COUNTRY = 'ADD_COUNTRY';

export type CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_NAME: CHANGE_NAME = 'CHANGE_NAME';
