export type REQUEST_TEABAGS = 'REQUEST_TEABAGS';
export const REQUEST_TEABAGS: REQUEST_TEABAGS = 'REQUEST_TEABAGS';

export type RECEIVE_TEABAGS = 'RECEIVE_TEABAGS';
export const RECEIVE_TEABAGS: RECEIVE_TEABAGS = 'RECEIVE_TEABAGS';

export type SEARCH_TERMS_ERROR = 'SEARCH_TERMS_ERROR';
export const SEARCH_TERMS_ERROR: SEARCH_TERMS_ERROR = 'SEARCH_TERMS_ERROR';

export type SEARCH_TERMS_CHANGED = 'SEARCH_TERMS_CHANGED';
export const SEARCH_TERMS_CHANGED: SEARCH_TERMS_CHANGED = 'SEARCH_TERMS_CHANGED';

export type ZOOM_IMAGE_TOGGLE = 'ZOOM_IMAGE_TOGGLE';
export const ZOOM_IMAGE_TOGGLE: ZOOM_IMAGE_TOGGLE = 'ZOOM_IMAGE_TOGGLE';

export type REQUEST_TEABAG = 'REQUEST_TEABAG';
export const REQUEST_TEABAG: REQUEST_TEABAG = 'REQUEST_TEABAG';

export type RECEIVE_TEABAG = 'RECEIVE_TEABAG';
export const RECEIVE_TEABAG: RECEIVE_TEABAG = 'RECEIVE_TEABAG';

export type CHANGE_BRAND = 'CHANGE_BRAND';
export const CHANGE_BRAND: CHANGE_BRAND = 'CHANGE_BRAND';

export type CLEAR_BRAND = 'CLEAR_BRAND';
export const CLEAR_BRAND: CLEAR_BRAND = 'CLEAR_BRAND';

export type CHANGE_BAGTYPE = 'CHANGE_BAGTYPE';
export const CHANGE_BAGTYPE: CHANGE_BAGTYPE = 'CHANGE_BAGTYPE';

export type CLEAR_BAGTYPE = 'CLEAR_BAGTYPE';
export const CLEAR_BAGTYPE: CLEAR_BAGTYPE = 'CLEAR_BAGTYPE';

export type CHANGE_COUNTRY = 'CHANGE_COUNTRY';
export const CHANGE_COUNTRY: CHANGE_COUNTRY = 'CHANGE_COUNTRY';

export type CLEAR_COUNTRY = 'CLEAR_COUNTRY';
export const CLEAR_COUNTRY: CLEAR_COUNTRY = 'CLEAR_COUNTRY';

export type CHANGE_SERIE = 'CHANGE_SERIE';
export const CHANGE_SERIE: CHANGE_SERIE = 'CHANGE_SERIE';

export type CHANGE_FLAVOUR = 'CHANGE_FLAVOUR';
export const CHANGE_FLAVOUR: CHANGE_FLAVOUR = 'CHANGE_FLAVOUR';

export type CHANGE_HALLMARK = 'CHANGE_HALLMARK';
export const CHANGE_HALLMARK: CHANGE_HALLMARK = 'CHANGE_HALLMARK';

export type CHANGE_SERIALNUMBER = 'CHANGE_SERIALNUMBER';
export const CHANGE_SERIALNUMBER: CHANGE_SERIALNUMBER = 'CHANGE_SERIALNUMBER';

export type SAVE_TEABAG = 'SAVE_TEABAG';
export const SAVE_TEABAG: SAVE_TEABAG = 'SAVE_TEABAG';
