export type REQUEST_BAGTYPE = 'REQUEST_BAGTYPE';
export const REQUEST_BAGTYPE: REQUEST_BAGTYPE = 'REQUEST_BAGTYPE';

export type RECIEVE_BAGTYPE = 'RECIEVE_BAGTYPE';
export const RECIEVE_BAGTYPE: RECIEVE_BAGTYPE = 'RECIEVE_BAGTYPE';

export type ADD_BAGTYPE = 'ADD_BAGTYPE';
export const ADD_BAGTYPE: ADD_BAGTYPE = 'ADD_BAGTYPE';

export type CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_NAME: CHANGE_NAME = 'CHANGE_NAME';
